### ISSUE TITLE
Cannot build due to moved theme

### ISSUE THREAD

**Issue by mikehearn** [ButterCam/Mediator#1]
I can't build the project because the theme isn't in any known repository:

```
Could not resolve com.bybutter.compose:compose-jetbrains-theme:1.0.
Required by:
    project :desktop
```

Is it meant to be published to a public Maven repo?

**Comment by devkanro** [comment]
Yes, check [Compose JetBrains Theme](https://mvnrepository.com/artifact/com.bybutter.compose/compose-jetbrains-theme/1.0)

**Comment by devkanro** [comment]
Recommend use the tag [1.0.0](https://github.com/ButterCam/Mediator/tree/v1.0.0) to build.

I am refactoring the proxy, the main branch is not buildable.
