### ISSUE TITLE
Does this support inspecting Firestore grpc calls?

### ISSUE THREAD

**Issue by ColtonIdle** [ButterCam/Mediator#2]
Sorry if this is the wrong place for this question but there isn't a "Discussions" tab on this repo.

I'm trying to inspect firebase firestore traffic which uses grpc. Would this be possible using Mediator?

**Comment by devkanro** [comment]
Mediator not support tls gRPC traffic now, I am refactor the proxy make it support tls.

If the firebase firestore traffic use the gRPC with tls, Mediator can't work with it.

**Comment by ColtonIdle** [comment]
Okay. I will try with charles. Thank you!

**Comment by devkanro** [comment]
I am pleased to inform you that Mediator will support gRPC/TLS requests in the next release.

We are currently testing the feature, so if you are interested in it, please leave a comment here and I will provide you with a beta version.

**Comment by ColtonIdle** [comment]
Do you know if it works with Firestore? If so, I'd pay money for that. Let me know!!!!!

**Comment by devkanro** [comment]
@ColtonIdle 

I don't know if Mediator works with Firestore, you can try it.

In theory, Mediator works with any gRPC service that supports service reflection.

Before applying Mediator to Firestore, you first need to confirm the following:

1. Does Firestore use gRPC as an API?
2. Does Firestore support service reflection?

We expect to add support for gRPC servers that do not support service reflection in the next version, but the premise is that you must have the proto source code of the API, or a binary description file.

**Comment by devkanro** [comment]
@ColtonIdle 
After some searching in github, the good news is firestore using gRPC.

You can found the protos here:
https://github.com/googleapis/java-firestore/blob/main/proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/firestore.proto

But we don't know does Firestore support service reflection? If it don't support it, you can wait our next release.

**Comment by devkanro** [comment]
@ColtonIdle 
Another good news here!

After 1.4.2 version, you can decode the gRPC message by proto source file.

You can download firestore proto files from [here](https://github.com/firebase/firebase-js-sdk/tree/master/packages/firestore/src/protos).

Configure the proto root in mediator server rule follow [the document](https://github.com/ButterCam/Mediator#resolve-messages).

Then you can decode the firestore api, don't forgot [install the Mediator Root Certificate](https://github.com/ButterCam/Mediator#https-support).

Check the ReadMe for more information.

**Comment by ColtonIdle** [comment]
@devkanro thanks for the instructions. I gave this a try on my android device just now.

I set up my devices WiFi to have a manual proxy set to my machine and now I can see traffic on mediator. I tried to install the mediator root certificate, but the file doesn't download wehn i click the link on my android device. 

<img width="389" alt="2022-09-07 at 22 29 17" src="https://user-images.githubusercontent.com/31751141/189020360-511644b5-2683-4fb0-8a53-89c5f86b354d.png">

**Comment by ColtonIdle** [comment]
Also please let me know if this is how I would setup the proto rule
<img width="912" alt="2022-09-07 at 22 49 38" src="https://user-images.githubusercontent.com/31751141/189022792-ccbd6388-00ce-4ac7-8483-03cfe41a97c4.png">

**Comment by ColtonIdle** [comment]
please also let me know if theres a way to donate to the project. thanks

**Comment by devkanro** [comment]
> I set up my devices WiFi to have a manual proxy set to my machine and now I can see traffic on mediator. I tried to install the mediator root certificate, but the file doesn't download when i click the link on my android device.

This seems odd because the Echo Service shows the address you accessed the certificate (/mediatorRoot.cer), and in theory when accessing the certificate path, the Echo Service will not be used.

> Also please let me know if this is how I would setup the proto rule
If you don't need rewrite the host, do not check the rewrite checkbox

Other settings are correct

**Comment by devkanro** [comment]
Can you download it from your PC or Mac, then transfer to your Android.

**Comment by ColtonIdle** [comment]
Okay. Downloading to my mac worked. Going to email the file to myself.

Accessing gmail on my android device with the proxy setup doesn't seem to work though which is weird. Ideas?

**Comment by devkanro** [comment]
> Accessing gmail on my android device with the proxy setup doesn't seem to work though which is weird. Ideas?

Mediator only support the gRPC request in proxy, when you are in a non-gRPC scenario, the proxy should not be enabled.

**Comment by devkanro** [comment]
Another weird thing is that Echo Service doesn't print Request Host like `GET http://192.168.1.1:8888/mediatorRoot.cer`

I don't know why your android is showing like this.

**Comment by ColtonIdle** [comment]
yeah. thats what i expected. all non-frpc traffic just works. but it doesn't.

it looks like once i set my proxy up to my mac with mediator running, i just lose my internet. i disabled the proxy. installed the CA certificate and installed it on my device. connected back to the proxy and can see that traffic is showing in mediator

**Comment by devkanro** [comment]
<img width="1253" alt="截屏2022-09-08 11 24 46" src="https://user-images.githubusercontent.com/9367842/189027907-165f5f42-5214-4ecf-a7f0-5c94deb563ae.png">

Notice the path after GET string do not include the host.

**Comment by ColtonIdle** [comment]
if I visit http://192.168.1.168:8888/mediatorRoot on my mac I see

<img width="993" alt="2022-09-07 at 23 33 10" src="https://user-images.githubusercontent.com/31751141/189028237-ffac2576-8fd0-46ea-9ab5-59de9282d01b.png">

**Comment by ColtonIdle** [comment]
i do see traffic from my android device. let me know if you think i can debug this somehow. also. let me know if you have a donation/patreon/github sponsor setup. thank you. i really would like to help make firestore data inspection a reality. 

<img width="895" alt="2022-09-07 at 23 35 10" src="https://user-images.githubusercontent.com/31751141/189028490-3420004b-e464-4349-8657-5bbe7db3d39b.png">

**Comment by ColtonIdle** [comment]
I have used both charles proxy and proxyman in the past. I wonder if any of their port numbers are messing with mediator. i made sure that both charles and proxyman are shutdown though and that my android device is not pointed to either of those port numbers.

**Comment by devkanro** [comment]
> yeah. thats what i expected. all non-frpc traffic just works. but it doesn't.
> 
> it looks like once i set my proxy up to my mac with mediator running, i just lose my internet. i disabled the proxy. installed the CA certificate and installed it on my device. connected back to the proxy and can see that traffic is showing in mediator

Ummm, maybe in the next version I can implement transparent transmission for non-grpc traffic.

**Comment by devkanro** [comment]
@ColtonIdle 
You should not set proxy in your wifi, the Java gRPC client proxy should be setting by those code:

```Kotlin
ManagedChannelBuilder.forAddress("foo.barapis.com", 9000)
    .usePlaintext()
    .proxyDetector {
        HttpConnectProxiedSocketAddress.newBuilder()
            .setTargetAddress(it as InetSocketAddress)
            .setProxyAddress(InetSocketAddress("<YOUR PC/MAC IP>", 8888))
            .build()
    }
    .build()
```

**Comment by ColtonIdle** [comment]
Interesting. Typically I set the proxy for charles and proxyman in my wifi settings.

I will try including your snippet above in my android App class

**Comment by devkanro** [comment]
> Interesting. Typically I set the proxy for charles and proxyman in my wifi settings.
> 
> I will try including your snippet above in my android App class

Yes, because most gRPC client will not use the system proxy setting, so you need config it by your self.

**Comment by ColtonIdle** [comment]
ManagedChannelBuilder.forAddress("firestore.googleapis.com", 443)
      .usePlaintext()
      .proxyDetector {
        HttpConnectProxiedSocketAddress.newBuilder()
          .setTargetAddress(it as InetSocketAddress)
          .setProxyAddress(InetSocketAddress("192.168.1.168", 8889))
          .build()
      }
      .build()

(i changed mediator to use :8889)

I dont see any traffic in mediator now. I wonder if firestore.googleapis.com is not the right address

**Comment by devkanro** [comment]
I found the FirestoreClient can accept a FirestoreStub.

You can build the FirestoreStub with 

```Kotlin
val channel = ManagedChannelBuilder.forAddress("firestore.googleapis.com", 443)
  .uuseTransportSecurity()
  .proxyDetector {
    HttpConnectProxiedSocketAddress.newBuilder()
      .setTargetAddress(it as InetSocketAddress)
      .setProxyAddress(InetSocketAddress("192.168.1.168", 8889))
      .build()
  }
  .build()

val stub = FirestoreStub(channel)

val client = FirestoreClient(stub)
```

**Comment by ColtonIdle** [comment]
<img width="683" alt="2022-09-07 at 23 55 18" src="https://user-images.githubusercontent.com/31751141/189030784-92e74967-f36e-40fb-b03e-3bf2649d9e94.png">

**Comment by devkanro** [comment]
Ummmm...repleace with

```Kotlin
val stub = FirestoreGrpc.newStub(channel)
```

**Comment by devkanro** [comment]
And

```Kotlin
val client = FirestoreClient.create(stub)
```

**Comment by ColtonIdle** [comment]
Getting closer!
<img width="488" alt="2022-09-08 at 00 00 51" src="https://user-images.githubusercontent.com/31751141/189031452-3a67f9dc-9e66-48a0-bca2-c79c3cd5de8f.png">

**Comment by devkanro** [comment]
Ummm...it should a create method here 
https://github.com/googleapis/java-firestore/blob/main/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreClient.java#L180

**Comment by ColtonIdle** [comment]
I think I technically use https://github.com/firebase/firebase-android-sdk but I thought it just deferred to java-firestore. hmm

**Comment by ColtonIdle** [comment]
https://github.com/firebase/firebase-android-sdk/blob/a50da9f8416ed35df3b1f80f05e5e91c440e6aa1/firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java

**Comment by devkanro** [comment]
It seem an wrapper with auth info for FirestoreClient in firestore-java

**Comment by devkanro** [comment]
Need to find some way to create FirestoreClient with our channel or stub

**Comment by ColtonIdle** [comment]
okay. i will keep looking. let me know if you find anything. so CLOSE!

**Comment by devkanro** [comment]
Try to see if there is a configuration for the proxy in FirebaseFirestoreSettings

**Comment by ColtonIdle** [comment]
It doesn't look like it unfortunately

<img width="803" alt="2022-09-08 at 00 11 37" src="https://user-images.githubusercontent.com/31751141/189032588-ac89e810-d31e-419e-bafe-be91e61d35ce.png">

**Comment by ColtonIdle** [comment]
Just 4 options available in firestore settings

**Comment by ColtonIdle** [comment]
Created a feature request on firebase android. maybe someone there can help.

**Comment by devkanro** [comment]
Create some breakpoint, to found how the firebase stub created in firebase-android-sdk

**Comment by ColtonIdle** [comment]
Yeah. I'm going to do that first thing tomorrow. about 4 hours past my bedtime. 😭 💤

**Comment by devkanro** [comment]
Hahaha I'm going to have some lunch too

**Comment by ColtonIdle** [comment]
looks like its created here. but yeah. thanks again for the help. i feel like im so close to having some way of inspecting firestore calls lol. its so hard not having ANY insight
<img width="884" alt="2022-09-08 at 00 23 01" src="https://user-images.githubusercontent.com/31751141/189033785-ed9ae98d-76b1-4c99-92ca-a01bd8798826.png">

**Comment by devkanro** [comment]
Maybe you can clone their code and change it from here
https://github.com/firebase/firebase-android-sdk/blob/c35626a475cfcfc702586a0df09718b11a7427d3/firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java#L109

Then compile one yourself

**Comment by ColtonIdle** [comment]
Thanks. I have never had to compile an external library like this myself... but hopefully I can make it work. I hope that firestore can also add this. We'll see how my feature request goes. 😄

**Comment by devkanro** [comment]
I built one for you. check it.

[maven.zip](https://github.com/ButterCam/Mediator/files/9529797/maven.zip)

Unzip in your ~/.m2, merge the repository dir.

Add mavenLocal to your build.gradle repository.

Use the `com.google.firebase:firebase-firestore:24.3.1-SNAPSHOT`

You can found the FirebaseFirestoreSettings class have new property named 'proxy', set it to `<YOU-PC-IP>:8888`.

**Comment by devkanro** [comment]
The source code is here
https://github.com/devkanro/firebase-android-sdk/commit/e9208e1961964da08a599f5318986072754356c6

**Comment by ColtonIdle** [comment]
Downloaded, placed in .m2, hit merge instead of replace. added mavenLocal() and added that dep SNAPSHOT you posted. Set the proxy on firestoreSettings... building and running now. 🤞

**Comment by ColtonIdle** [comment]
java.lang.IllegalStateException: The proxy address 192.168.1.168:8888 is not resolved

**Comment by ColtonIdle** [comment]
Confirmed that the certificate is installed on my android device and that mediator is running on my machine.

**Comment by ColtonIdle** [comment]
Just for the sake of making sure that the connection works correctly, I'm going to set my wifi proxy (on my android) to my PC/mediator. just to see if any content starts to populate there again.

**Comment by devkanro** [comment]
> (i changed mediator to use :8889)

Are you still using 8889?

**Comment by devkanro** [comment]
Try this one.
[09090958.zip](https://github.com/ButterCam/Mediator/files/9531722/09090958.zip)

Source code here.
https://github.com/devkanro/firebase-android-sdk/commit/07d271c38e854ccff00390fa3cd6a246a858b360

**Comment by devkanro** [comment]
I updated the [HTTPS Support](https://github.com/ButterCam/Mediator#https-support) document.

You should update your Android Manifest file to trust user certificates.

---

In Android 7.0 or later, you need config the networkSecurityConfig in `app/src/main/AndroidManifest.xml` to trust user
certificates.

```xml
<application
        android:name=".ApplicationClass"
        android:allowBackup="true"
        android:hardwareAccelerated="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:networkSecurityConfig="@xml/network_security_config"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
```

With a corresponding `network_security_config.xml` in `app/src/main/res/xml/`:

1. Just trust user certificates in debug mode.

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <debug-overrides>
        <trust-anchors>
            <certificates src="user" />
        </trust-anchors>
    </debug-overrides>
</network-security-config>
```

2. Trust user certificates in release mode (Same as Android 6.0 and lower).

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
   <base-config cleartextTrafficPermitted="true">
      <trust-anchors>
         <certificates src="system" />
         <certificates src="user" />
      </trust-anchors>
   </base-config>
</network-security-config>
```

More information about
Android's [networkSecurityConfig](https://developer.android.com/training/articles/security-config).

**Comment by ColtonIdle** [comment]
Yep. I already have the trust certificates because I use ssl proxying with charles and proxyman.

I will try the new version soon!

**Comment by ColtonIdle** [comment]
`    com.google.firebase.firestore.FirebaseFirestoreException: Failed to get document because the client is offline.`
Looks like I need better error handling, but I will also try to debug my security config or certificate. It's weird though, because I'm fairly familiar with the process because of how often I use ssl proxying with charles and proxyman.

I'll keep you in the loop, but let me know if you can think of any debugging steps.

**Comment by devkanro** [comment]
Are any calls showing in Mediator?

**Comment by ColtonIdle** [comment]
I disabled my server rule. Run my app (it eventually crashes) but I see this in mediator. So there's definitely something working here.

![2022-09-10 at 10 12 18](https://user-images.githubusercontent.com/31751141/189487237-4584e66f-7776-477c-b34d-4fa1cdd92112.png)

**Comment by ColtonIdle** [comment]
@devkanro any ideas

**Comment by devkanro** [comment]
It seem the cert do not be install to client or stub.

**Comment by devkanro** [comment]
Or your server rule don't contains firestore.googleapis.com:443

**Comment by ColtonIdle** [comment]
I just tried again. My cert is indeed installed and server rule contains firestore.googleapis.com:443
ill try debugging again in a few days. 😭
