### ISSUE TITLE
how to install mediator on archlinux?

### ISSUE THREAD

**Issue by Gictorbit** [ButterCam/Mediator#4]
Hello thank you for your great job, I tried `deb` package to install Linux version of your app on my Arch Linux distro using [debtap](https://github.com/helixarch/debtap), but It didn't work can you please provide installer for `aur helper` repository? So we can try it easier using `yay` or other installer scripts

**Comment by devkanro** [comment]
The `deb` package is packaged by compose desktop plugin, I have no knowledge about how it works with linux.

This issue maybe can provide some information for you.
- JetBrains/compose-jb#596

**Comment by Gictorbit** [comment]
Thank you for your quick reply, here is what I did:
1- first I converted `deb` package to `pkg.tar.zst` using command below:
```sh
debtap mediator_1.4.3-1_amd64.deb
```
2- after that tried to install it using `pacman` which is official package manager of arch distros
```sh
sudo pacman -U --noconfirm mediator-1.4.3-1-x86_64.pkg.tar.zst
```
that failed by this error:
```sh
/tmp/alpm_LobEMY/.INSTALL: line 3: syntax error near unexpected token `}'
/tmp/alpm_LobEMY/.INSTALL: line 3: `}'
/usr/bin/bash: line 1: pre_upgrade: command not found
```

**Comment by devkanro** [comment]
Ummm, I don't know anything about `debtap`, maybe you can open an issue or create a discussion for [JetBrains/compose-jb](https://github.com/JetBrains/compose-jb/discussions).

If you just want to run mediator in your archlinux, you can clone this project and execute `./gradlew run`.

If you want to distribute executable to archlinux, you can use `./gradlew createDistributable` command to create distributable.  
The distribution will created in `./desktop/build/compose/binaries`, use tar command pack it, the consumer can just unpack it and exec it.

This project require JDK16+, JDK 17 is recommend.

**Comment by devkanro** [comment]
Is there anything else I can help with?
I will set this issue as closed, if you have other issues you can reopen it or create a new issue.
