### ISSUE TITLE
Does it work with Dart client ?

### ISSUE THREAD

**Issue by mbilbiesi** [ButterCam/Mediator#7]
Hello,

I have question if I can setup this tool using Dart https://github.com/grpc/grpc-dart ?

Regards,

**Comment by devkanro** [comment]
I think it should be available, just need to configure the proxy's link

**Comment by mbilbiesi** [comment]
I am wondering on how to set the proxy's link with grpc-dart; I could not find any documentation for this.

My client initialisation looks like 
```
  void initClient() {
    channel = ClientChannel(
      getBaseUrl(),
      port: 443,
      options: ChannelOptions(
        // credentials: const ChannelCredentials.insecure(),
        codecRegistry: CodecRegistry(
          codecs: const [GzipCodec(), IdentityCodec()],
        ),
      ),
    );
    stub = NativeGatewayServiceClient(channel);
  }
```

**Comment by devkanro** [comment]
Ohh, it seems grpc-dart don't support proxy yet

grpc/grpc-dart#33
